name: build train image
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu:22.04
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - uses: docker/setup-buildx-action@v3
      - uses: docker/build-push-action@v5
        with:
          file: ./train/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/train:v1