name: build train and inference image
on:
  push:
    branches:
      - main
jobs:
  build-train:
    runs-on: ubuntu-22.04
    steps:
      - uses: docker/setup-buildx-action@v3
      - run: |
          docker login -u ${{ secrets.ALIYUN_DOCKER_USERNAME }} ${{ secrets.ALIYUN_DOCKER_REGISTRY }} --password ${{ secrets.ALIYUN_DOCKER_PASSWORD }}
      - run: |
          wget https://github.com/yhw-miracle/TrainAI/releases/download/Train-Dockerfile/Dockerfile -O Dockerfile
      - run: |
          docker buildx build . --platform linux/amd64 --tag ${{ secrets.ALIYUN_DOCKER_REGISTRY }}/${{ secrets.ALIYUN_DOCKER_USERNAME }}/train:v1 --file Dockerfile --push
  # build-inferecne-train:
  #   runs-on: ubuntu-22.04
  #   steps:
  #     - uses: docker/login-action@v3
  #       with:
  #         registry: registry.cn-hangzhou.aliyuncs.com
  #         username: ${{ secrets.DOCKER_USERNAME }}
  #         password: ${{ secrets.DOCKER_PASSWORD }}
  #     - uses: docker/setup-buildx-action@v3
  #     - uses: docker/build-push-action@v5
  #       with:
  #         file: ./inference/Dockerfile
  #         push: true
  #         tags: ${{ secrets.DOCKER_USERNAME }}/inference:v1
