name: build train and inference image
on:
  push:
    branches:
      - main
jobs:
  build-train:
    runs-on: ubuntu-22.04
    steps:
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - uses: docker/build-push-action@v5
        with:
          file: ./train/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/train:v1
  sync-image:
    runs-on: ubuntu-22.04
    needs: build-train
    steps:
      - uses: hhyasdf/image-sync-action@1.1
        with:
          auth_file: ./auth.yaml
          image_file: ./train/train-image.yaml
          version: v1
          proc: 20
  # build-inferecne-train:
  #   runs-on: ubuntu-22.04
  #   steps:
  #     - uses: docker/login-action@v3
  #       with:
  #         registry: registry.cn-hangzhou.aliyuncs.com
  #         username: ${{ secrets.DOCKER_USERNAME }}
  #         password: ${{ secrets.DOCKER_PASSWORD }}
  #     - uses: docker/setup-buildx-action@v3
  #     - uses: docker/build-push-action@v5
  #       with:
  #         file: ./inference/Dockerfile
  #         push: true
  #         tags: ${{ secrets.DOCKER_USERNAME }}/inference:v1
